version: 2

references:
  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  build: &build
    docker:
      - image: gableroux/dotnet-mono-monogame:latest
    working_directory: ~/repo
    workspace: ~/repo/artifacts
    steps:
      - checkout
      - *attach_workspace
      - run: ci/build.sh
      - store_artifacts:
          path: ~/repo/artifacts/
jobs:
  windows:
    <<: *build
    environment:
      BUILD_PLATFORM: 'win-x64'
  linux:
    <<: *build
    environment:
      BUILD_PLATFORM: 'linux-x64'
  macos:
    <<: *build
    environment:
      BUILD_PLATFORM: 'osx-x64'
  deploy:
    docker:
      - image: dosowisko/butler:latest
    steps:
      - checkout
      - *attach_workspace
      - run: ci/deploy.sh

workflows:
  version: 2
  workflow:
    jobs:
      - windows
      - linux
      - macos
      - deploy:
          requires:
            - windows
            - linux
            - macos
          filters:
            branches:
              only:
                - master
                - circleci-deploy-itchio # TODO: delete this line once merge request is merged

